name: GitHub Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: Kaviyaselvan123
          filename: github-metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_followup: yes
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
